# Support Vector Machine

Este notebook apresenta um exemplo de classificação utilizando SVM para classificar os diferentes tipos de flores Iris.

O dataset utilizado para a obtenção do modelo possui 150 amostras com 4 atributos caracterísitcos de flores, que são eles:
* **sepal length:** Comprimento da sépala em centímetros
* **sepal width:** Largura da sépala em centímetros
* **petal length:** Comrpimento da pétala em centímetros
* **petal width:** Largura da pétala em centímetros

A classificação é feita para catergorizar a amostra em 3 tipos diferentes de flores Iris que são Setosa, Versicolour e Virginica.


# Carregamento dos dados

In [24]:
# Bibliotecas 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [40]:
dataset = pd.read_csv("Iris.csv"); 
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [41]:
dataset.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [46]:
X = dataset.iloc[:, 1:5].values
y = dataset.iloc[:,5].values

print(X[0:6,:])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]


#Separação do dataset em valores pra teste e trainamento

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=0)

# Treinamento do modelo

In [53]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear')
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

# Predição e validação

In [56]:
y_pred = classifier.predict(X_test)

In [57]:
from sklearn.metrics import accuracy_score

print("Acurácia: ", accuracy_score(y_test, y_pred)*100, "%")

Acurácia:  97.77777777777777 %
